# Generated by Django 2.1.2 on 2020-03-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('message', models.CharField(max_length=200, verbose_name='本文')),
                ('date', models.DateField(verbose_name='作成日')),
            ],
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
