# Generated by Django 2.1.2 on 2020-03-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200316_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedb',
            old_name='name',
            new_name='username',
        ),
    ]
